const getProductsV1 = require("./crud/getProducts.v1");
const getProductV1 = require("./crud/getProduct.v1");
const createProductV1 = require("./crud/createProduct.v1");
const updateProductV1 = require("./crud/updateProduct.v1");
const deleteProductV1 = require("./crud/deleteProduct.v1");
const getVariantsV1 = require("./crud/getVariants.v1");
const createVariantV1 = require("./crud/createVariant.v1");
const updateVariantV1 = require("./crud/updateVariant.v1");
const deleteVariantV1 = require("./crud/deleteVariant.v1");

exports.getProducts = getProductsV1;
exports.getProduct = getProductV1;
exports.createProduct = createProductV1;
exports.updateProduct = updateProductV1;
exports.deleteProduct = deleteProductV1;
exports.getVariants = getVariantsV1;
exports.createVariant = createVariantV1;
exports.updateVariant = updateVariantV1;
exports.deleteVariant = deleteVariantV1;
